---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./botkube/ks.yaml
  - ./jaeger/ks.yaml
  - ./otel/ks.yaml
  # - ./prometheus/ks.yaml
  - ./speedtest-exporter/ks.yaml
  - ./nut-exporter/ks.yaml
