---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
configMapGenerator:
  - name: mediamtx-config
    files:
      - mediamtx.yaml
generatorOptions:
  disableNameSuffixHash: true
