---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
  - dns.yaml
  - rclone.enc.yaml
  - rclone.job.yaml
configMapGenerator:
  - name: mediamtx-config
    files:
      - mediamtx.yml
generatorOptions:
  disableNameSuffixHash: true
