---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 6.29.5
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  dependsOn:
    - name: traefik-external
      namespace: network-system
    - name: ceph-cluster
      namespace: rook-ceph
  timeout: 10m0s
  values:
    image:
      repository: grafana/grafana
      tag: 8.5.3
      sha: ""
      pullPolicy: IfNotPresent
