---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - angelnu-charts.yaml
  - ark-server-charts.yaml
  - ark-server-charts-custom.yaml
  - authentik-charts.yaml
  - backube-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - botkube-charts.yaml
  - cnpg.yaml
  - coredns-charts.yaml
  - crossplane-charts.yaml
  - crutonjohn-charts.yaml
  - democratic-csi-charts.yaml
  - dex-chart.yaml
  - emqx-charts.yaml
  - fairwinds-charts.yaml
  - flagger-charts.yaml
  - gatekeeper-charts.yaml
  - grafana-charts.yaml
  - itzg-minecraft-charts.yaml
  - jaeger-charts.yaml
  - jameswynn-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kubernetes-nginx-ingress.yaml
  - k8s-sigs-descheduler-charts.yaml
  - k8s-sigs-external-dns-charts.yaml
  - kubernetes-stable-charts.yaml
  - litmuschaos-charts.yaml
  - longhorn-charts.yaml
  - nextcloud-charts.yaml
  - node-feature-discovery-chart.yaml
  - oauth2-proxy-chart.yaml
  - openfaas-charts.yaml
  - opentelemetry-charts.yaml
  - piraeus-charts.yaml
  - replicator-charts.yaml
  - signoz-charts.yaml
  - smallstep-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - victoriametrics-charts.yaml
  - rook-charts.yaml
