---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - angelnu-charts.yaml
  - authentik-charts.yaml
  - banzaicloud-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - botkube-charts.yaml
  - coredns-charts.yaml
  - crossplane-charts.yaml
  - crutonjohn-charts.yaml
  - democratic-csi-charts.yaml
  - dex-chart.yaml
  - emqx-charts.yaml
  - fairwinds-charts.yaml
  - flagger-charts.yaml
  - gatekeeper-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - inlets-charts.yaml
  - istio-charts.yaml
  - itzg-minecraft-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kubernetes-nginx-ingress.yaml
  - k8s-sigs-descheduler-charts.yaml
  - k8s-sigs-external-dns-charts.yaml
  - kubernetes-stable-charts.yaml
  - litmuschaos-charts.yaml
  - longhorn-charts.yaml
  - metallb-charts.yaml
  - nextcloud-charts.yaml
  - node-feature-discovery-chart.yaml
  - oauth2-proxy-chart.yaml
  - openfaas-charts.yaml
  - opentelemetry-charts.yaml
  - replicator-charts.yaml
  - signoz-charts.yaml
  - stakater-charts.yaml
  - tanzu-charts.yaml
  - traefik-charts.yaml
  - vernemq-charts.yaml
  - victoriametrics-charts.yaml
  - weaveworks-kured-charts.yaml
