---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  - ./intel-gpu-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./nvidia-gpu-operator/ks.yaml
  - ./reloader/ks.yaml
  - ./replicator/ks.yaml
