---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: syncthing
  annotations:
    kubernetes.io/ingress.class: "traefik-external"
    external-dns.alpha.kubernetes.io/hostname: music.${FAMILY_DOMAIN}
    external-dns.alpha.kubernetes.io/target: ${DYNAMIC_DOMAIN}
    external-dns/public: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`bs-sync.${FAMILY_DOMAIN}`)"
      priority: 10
      middlewares:
        - name: oauth-auth
          namespace: auth-system
        - name: oauth-errors
          namespace: auth-system
      services:
        - name: syncthing
          port: 8384
    - kind: Rule
      match: "Host(`bs-sync.${FAMILY_DOMAIN}`) && PathPrefix(`/oauth2/`)"
      priority: 15
      middlewares:
        - name: oauth-headers
          namespace: auth-system
      services:
        - name: google-auth-oauth2-proxy
          namespace: auth-system
          port: 80
  tls:
    secretName: heyjohn-wildcard-certificate
    domains:
      - main: bs-sync.${FAMILY_DOMAIN}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: syncthing
  annotations:
    external-dns/public: "true"
spec:
  endpoints:
    - dnsName: bs-sync.${FAMILY_DOMAIN}
      recordTTL: 300
      recordType: CNAME
      targets:
        - ${DYNAMIC_DOMAIN}
