---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/auth-system/oauth2-proxy
  - ingressroute.yaml
  - middleware.yaml
  - google.enc.yaml
patches:
  - path: patch.oauth2-proxy.yaml
