---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  CLUSTER_POD_CIDR: "10.244.0.0/16"
  CLUSTER_SVC_CIDR: "10.96.0.0/12"
  CLUSTER_DOMAIN_CERT: crj-wildcard-certificate
  CLUSTER_LB_INGRESS_INTERNAL: "192.168.130.100"
  CLUSTER_LB_INGRESS_EXTERNAL: "192.168.130.101"
  CLUSTER_LB_BLOCKY: "192.168.130.102"
  CLUSTER_LB_UNIFI: "192.168.130.103"
  CLUSTER_LB_SSHFS: "192.168.130.104"
  CLUSTER_LB_LOKI: "192.168.130.105"
  CLUSTER_LB_SYSLOGNG: "192.168.130.106"
  CLUSTER_LB_HOMECRAFT: "192.168.130.107"
  CLUSTER_LB_HOME_ASSISTANT: "192.168.130.108"
  CLUSTER_LB_MQTT: "192.168.130.109"
