---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-generic
data:
  # L2 Announcements have been removed
  # now using BGP but i am
  # KEEPING THESE COMMENTS FOR FUTURE USE
  # production 192.168.130.96/28
  # 192.168.130.97 - 192.168.130.110
  # CLUSTER_LB_PRODUCTION_RANGE: "192.168.130.96/28"
  CLUSTER_LB_INGRESS_EXTERNAL: "192.168.142.1"
  CLUSTER_LB_INGRESS_INTERNAL: "192.168.142.2"
  CLUSTER_LB_OTEL_SYSLOG_TCP: "192.168.142.3"
  CLUSTER_LB_PROMETHEUS: "192.168.142.4"
  CLUSTER_LB_MUSIC_SYNC: "192.168.142.5"
  CLUSTER_LB_ARK_SERVER: "192.168.142.6"
  CLUSTER_LB_MESH_API_MAIN: "192.168.142.7"
  CLUSTER_LB_MESH_API_CASA: "192.168.142.8"
  CLUSTER_LB_OTEL_SYSLOG_UDP: "192.168.142.9"
  CLUSTER_LB_HOME_ASSISTANT: "192.168.142.10"
  CLUSTER_LB_MQTT: "192.168.142.11"
  CLUSTER_LB_CNPG: "192.168.142.12"
  CLUSTER_LB_JAEGER: "192.168.142.13"
  CLUSTER_LB_SMALLSTEP: "192.168.142.14"
  LOCAL_TIMEZONE: "America/New_York"
