---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-template.yaml
configMapGenerator:
  - name: llama-configmap
    files:
      - config.yaml=./config/llama-config.yaml
generatorOptions:
  disableNameSuffixHash: true
