---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: librespeed
  annotations:
    kubernetes.io/ingress.class: "traefik-external"
    external-dns.alpha.kubernetes.io/hostname: speedof.${FAMILY_DOMAIN}
    external-dns.alpha.kubernetes.io/target: ${DYNAMIC_DOMAIN}
    external-dns/public: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`speedof.${FAMILY_DOMAIN}`)"
      services:
        - name: openspeedtest-librespeed
          port: 3000
  tls:
    secretName: heyjohn-wildcard-certificate
    domains:
      - main: speedof.${FAMILY_DOMAIN}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: librespeed
  annotations:
    external-dns/public: "true"
spec:
  endpoints:
    - dnsName: speedof.${FAMILY_DOMAIN}
      recordTTL: 300
      recordType: CNAME
      targets:
        - ${DYNAMIC_DOMAIN}
