---
- name: include token creation tasks
  include_tasks: token.yml
  when: not cluster_node_configured

- name: Show kubeadm-join config file
  debug:
    msg: "{{ lookup('template', '../templates/kubeadm-join.yml.j2') }}"
  when: ansible_check_mode

- name: generate kubeadm join configuration
  template:
    src: kubeadm-join.yml.j2
    dest: /etc/kubernetes/kubeadm-join.yml
  when: not cluster_node_configured

- name: join node to cluster
  command:
    cmd: kubeadm join --config /etc/kubernetes/kubeadm-join.yml
    creates: /etc/kubernetes/kubelet.conf
