---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr
  annotations:
    kubernetes.io/ingress.class: "traefik-external"
    external-dns.alpha.kubernetes.io/hostname: lidarr.${FAMILY_DOMAIN}
    external-dns.alpha.kubernetes.io/target: ${DYNAMIC_DOMAIN}
    external-dns/public: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`lidarr.${FAMILY_DOMAIN}`)"
      middlewares:
        - name: authentik
          namespace: auth-system
      priority: 10
      services:
        - name: lidarr
          port: 8686
    - kind: Rule
      match: "Host(`lidarr.${FAMILY_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)"
      priority: 15
      services:
        - kind: Service
          name: ak-outpost-authentik-embedded-outpost
          namespace: auth-system
          port: 9000
  tls:
    secretName: heyjohn-wildcard-certificate
    domains:
      - main: lidarr.${FAMILY_DOMAIN}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: lidarr
  annotations:
    external-dns/public: "true"
spec:
  endpoints:
    - dnsName: lidarr.${FAMILY_DOMAIN}
      recordTTL: 300
      recordType: CNAME
      targets:
        - ${DYNAMIC_DOMAIN}
