# enable deploying docker pull through cache
docker_cache_enable: true
# enable Traefik proxy on your registry host
cache_traefik_enable: true
# enable tls encryption of http traffic on registry
cache_tls_enable: true
# the FQDN that your registry should be reachable at locally
# this can also be an IP address so long as cache_tls_enable is false
cache_registry_fqdn: registry.crutonjohn.com
# the FQDN that your traefik dashboard will be available at
cache_traefik_dashboard_fqdn: traefik.crutonjohn.com
# Requisite packages for docker cache
# cache_packages:
#   - docker-compose
# Dockerhub user name
cache_docker_login_user: crutonjohn
# Dockerhub login access token generated at https://hub.docker.com/settings/security
cache_docker_access_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65343635373935643665306637633737363564636565326632323230363436666232316231663564
          6263613530316431643431313061333337633134646237350a383965343665303662636566623530
          35303534336534396135363931613336346165363637366237646434386366316634333337646130
          3237326462306238610a353765353261646266636563333262323363636234366163633163383633
          36343763613436626539623737363035396133343832396339396632353938343530393364623534
          6166343230663539653933363265393965343362633738633932
# Host path to mount into docker cache
cache_docker_host_path: /mnt/registry
# Email to associate with Lets Encrypt cert
cache_traefik_le_tls_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35363237343161616131383366323365346430313165343339623561373136363132326263363534
          3536376534623036353133313262623234343630373133350a353763366135326436633634366531
          63303663323131363631383834343361636263326263666263623663363330626536666230353436
          3232323430346262630a623335316438313536623530383866393338646263376466323731656432
          38373032336131386234313731313239323261663236616363313133613337613531316265653538
          3063373462663832343733356462633431303265663136303365
# Lets Encrypt ACME api to use; either 'prod' or 'staging'
cache_traefik_le_acme_environment: prod
# AWS access key for use with Lets Encrypt DNS01 challenge (Route 53)
cache_traefik_aws_access_key_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30353532306363613731643062616430303935393231643836306363393235653232643364373731
          6532333863663562646536366634343563393538383737320a666331636564393265656130313466
          38353864626130313339383362323739613730383461363465613861626638613333303032323235
          3561326232363633390a623238386332326538623139396432373464366632633466346235343461
          32643636663938666138366637353965306634303639613835303336323262663437
cache_traefik_aws_secret_access_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32623661623633643761303732313862633164326563333834653232643335643230343231393835
          3061303738366134643663623134666539393164313561390a353537303536363830313034376438
          38643466623231303539613538613336373866633234646566303735336338366234356337626461
          3130646638653462360a373262396566623663653866346633386435393439316138346662336161
          31373733616333316135333965383937656430643733326631316434323234653733343838666531
          6330396536316666613865326161666634633161363737626438
# AWS Region in which your Route 53 records exist
cache_traefik_aws_region: us-east-1
# AWS nameservers to verify domain ownership
cache_traefik_aws_resolver_ips:
 - "205.251.194.46"
 - "205.251.197.222"
