---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-${CLUSTER_NAME}
data:
  CLUSTER_POD_CIDR: "10.42.0.0/16"
  CLUSTER_SVC_CIDR: "10.43.0.0/16"
  OLD_CLUSTER_LB_CIDR: "192.168.130.96/28"
  CLUSTER_LB_CIDR: "192.168.142.0/24"
  HOME_NETWORK_CIDR: "192.168.128.0/20"
  HEADSCALE_NETWORK_CIDR: "100.64.0.0/10"
  CLUSTER_NAME: "production"
