---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ntfy-deployment.yaml
  - ntfy-svc.yaml
  - ntfy-pvc.yaml
  - ntfy-ingress.yaml
configMapGenerator:
  - name: server-config
    files:
      - server.yml
