---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./k8s-nodes.yaml
  - ./desktops.yaml
  - ./omada.yaml
  - ./monitoring.yaml
  - ./home-automation.yaml
  - ./workbench.yaml
  - ./pihole.yaml
