---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./k8s-nodes.yaml
  - ./omada.yaml
  - ./monitoring.yaml
  - ./home-automation.yaml
  - ./perturabo.yaml
  - ./workstations.yaml
  - ./pihole.yaml
  - ./gaming.yaml
