---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/b732974574feddffd85a2f759d9c156e6cb06ddb/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prometheus
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/apps/env/production/observability/prometheus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-main
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-aws
  dependsOn:
    - name: cilium-bgp
  postBuild:
    substitute:
      APP: *app
      INGRESSROUTE_SUBDOMAIN: "prom-lyh"
    substituteFrom:
      - kind: Secret
        name: secrets-${CLUSTER_NAME}
      - kind: Secret
        name: secrets-generic
      - kind: ConfigMap
        name: settings-generic
      - kind: ConfigMap
        name: settings-${CLUSTER_NAME}
