---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/media/lidarr
  - ingressroute.yaml
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: prowlarr
    target:
      kind: HelmRelease
      name: .*
  - path: app.patch.yaml
