---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app traefik-internal
  namespace: flux-system
spec:
  targetNamespace: network-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/apps/env/production/network-system/traefik/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-aws
  dependsOn:
    - name: cilium-bgp
    - name: certificates
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - kind: Secret
        name: secrets-${CLUSTER_NAME}
      - kind: Secret
        name: secrets-generic
      - kind: ConfigMap
        name: settings-generic
      - kind: ConfigMap
        name: settings-${CLUSTER_NAME}
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app traefik-external
  namespace: flux-system
spec:
  targetNamespace: network-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/apps/env/production/network-system/traefik/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-aws
  dependsOn:
    - name: cilium-bgp
    - name: certificates
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - kind: Secret
        name: secrets-${CLUSTER_NAME}
      - kind: Secret
        name: secrets-generic
      - kind: ConfigMap
        name: settings-generic
      - kind: ConfigMap
        name: settings-${CLUSTER_NAME}
