---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/home/mosquitto
  - secret.enc.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./config/mosquitto.conf
configurations:
  - ./patches/kustomizeconfig.yaml
patches:
  - path: patch.mosquitto.yaml
